name: carvajal_autotech
description: A modern quiz application with admin and student interfaces.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.0.2

  # Estado y Arquitectura
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # HTTP y API
  http: ^1.1.0
  dio: ^5.3.2

  # Almacenamiento local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI y Animaciones
  animations: ^2.0.8
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # Utilidades
  intl: ^0.18.1
  uuid: ^4.1.0

  # Iconos
  cupertino_icons: ^1.0.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
